# Generated by Django 2.1.1 on 2018-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=50)),
                ('rok_prod', models.CharField(max_length=10)),
                ('nadwozie', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
            ],
        ),
    ]
