# Generated by Django 2.1.1 on 2018-09-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='engines.Engine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='nadwozie',
            field=models.CharField(blank=True, choices=[('hatchback', 'hatchbag')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rok_prod',
            field=models.IntegerField(),
        ),
    ]
