# Generated by Django 2.1.1 on 2018-09-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Engine',
        ),
    ]
