# Generated by Django 2.1.1 on 2018-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0002_auto_20180930_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='paliwo',
        ),
        migrations.AddField(
            model_name='engine',
            name='rodzaj',
            field=models.CharField(blank=True, choices=[('benzyna', 'benzyna')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='ilosc_cylindrow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='pojemnosc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
